### ISSUE TITLE
Use local Composer dependency for build

### ISSUE THREAD

**Issue by Craige** [escapestudios/Symfony2-coding-standard#19]
Can we install PHPUnit locally through composer and use the composer installed versions of phpunit and phpcs for our build script?

The new build.xml section would look something like this

    <target name="phpunit" description="Run unit tests with PHPUnit" depends="vendor">
        <exec executable="${basedir}/vendor/bin/phpunit" failonerror="true" >
            <arg value="--filter=Symfony2_*" />
            <arg value="${basedir}/vendor/squizlabs/php_codesniffer/tests/AllTests.php" />
        </exec>
    </target>

    <target name="phpcs" description="Find coding standard violations using PHP Code Sniffer" depends="vendor">
        <exec executable="${basedir}/vendor/bin/phpcs">
            <arg value="--standard=${phpcs.standard}" />
            <arg value="--ignore=vendor/*" /> 
            <arg path="${basedir}" />
        </exec>
    </target>

This will remove the external PHPUnit and PHPCS dependencies, as well as allowing us to enforce the version requirements of both of these tools.

**Comment by djoos** [comment]
Hi @Craige,

I would rather leave the way "phpunit" and "phpcs" commands are made available up to the developer to decide. I prefer to have PHPUnit and PHP_CodeSniffer installed when provisioning my development machine before any project is even checked out/started...

Kind regards.
David
