### ISSUE TITLE
Missing return tag from closure

### ISSUE THREAD

**Issue by jonag** [escapestudios/Symfony2-coding-standard#33]
phpcs reports a missing return tag if the method has no return value but contains a closure which returns a value.

For example, this function

    /**
     * @param \Symfony\Component\Form\FormEvent $event
     */
    public function onPreSetData(FormEvent $event)
    {
        $form = $event->getForm();

        $form->add(
            'project',
            'entity',
            [
                'class' => 'AppBundle:Project',
                'choice_label' => 'name',
                'query_builder' => function (ProjectRepository $repository) {
                        return $repository->queryAll();
                },
                'empty_value' => 'search.all',
                'required' => false,
                'label' => 'project',
                'multiple' => true,
                'expanded' => false,
            ]
        );
    }

triggers the error `Missing @return tag in function comment`

**Comment by Soullivaneuh** [comment]
:+1:
