### ISSUE TITLE
Ruleset compatibility with PHP-CS-Fixer

### ISSUE THREAD

**Issue by haroldmodesto** [escapestudios/Symfony2-coding-standard#38]
I'm using PhpStorm and was pointed to this project in one of its tutorials. I would like to use this standard in conjunction with the [PHP-CS-Fixer] (https://github.com/FriendsOfPHP/PHP-CS-Fixer) by SensioLabs. 

Is the standard used compatible with the Symfony2 fixes that PHP-CS will attempt to do? Thanks!

**Comment by wickedOne** [comment]
yes it is.

php-cs-fixer applies even more rules than those enforced by this coding standard (e.g. yoda conditions for equality), but after applying php-cs-fixer, your code should be fully compatible with this coding standard.

if not, just open an issue over here and i'm quite sure one of the contributors will look into it.

**Comment by haroldmodesto** [comment]
Thanks again. Will resume today and test PHP-CS-Fixer. 

By the way I had to set minumum-stability to dev in composer.json before I could get Symfony2-coding-standard to install.
